### ISSUE TITLE
Incorrect behavior when marking tasks as completed in Todo List program

### ISSUE THREAD

**Issue by shivamsinha545** [shivamsinha545/Python-Projects#1]
I am using the Todo List program that uses file handling in Python to manage my tasks. The program has a function that allows me to mark a task as completed by inputting the serial number of the task. However, when I try to mark multiple tasks as completed, the program removes all tasks except the first one from the task.txt file.

For example, if I have 5 tasks in the task.txt file and I input the serial numbers 1, 2, 3, 4 as my user input, the program removes the 2nd, 3rd, 4th, and 5th lines from the task.txt file instead of removing 1st,2nd ,3rd and 4th line as stated by the user. This behavior is not expected and causes problems for me when I try to use the program.

I would appreciate it if someone could help me fix this issue. Thank you.

Link - https://github.com/shivamsinha545/Python-Projects/blob/master/Basic%20Projects/ToDo%20List/list.py

**Comment by anmoljhamb** [comment]
Hey! I'd like to help you out! If you'll assign me this issue, I'll get right on it!

**Comment by anmoljhamb** [comment]
Are you sure that your code is up to date here? The thing is, there is an error on line number 48 
```diff
-for number in len(numbers)
+for number in range(len(numbers))
```
We cannot iterate over an integer. We need an iterable. If I change the the code to this. The code is actually working fine. Check it out and let me know :)

**Comment by shivamsinha545** [comment]
If you have understood the code structure and its flow, then you can rewrite the markComplete() function.

**Comment by anmoljhamb** [comment]
Sure, I'll rewrite the markComplete() function.

**Comment by shivamsinha545** [comment]
That's great. Also, I have updated the code. There are no more compilation errors.

**Comment by anmoljhamb** [comment]
I just checkout the code, and the error was a really simple one, and can easily be overlooked. The thing is, when you're checking if a given `number` is in `numbers` or not, you're just forgetting one thing that, number is an index of the list, and therefore, starts with 0. So, as you mentioned in your issue. If you're entering 1, 2, 3, 4, it will mark the tasks 2nd, 3rd, 4th and 5th. Leaving you with the first task. It's a really simple fix. All you need to do is, add this single line, `number += 1`

```python
for number, line in enumerate(lines):
  number += 1
  if number not in numbers:
      fp.write(line)
```

**Comment by anmoljhamb** [comment]
Let me know if you understood what I am saying or not. Else I'll try to explain it in a better way.

**Comment by shivamsinha545** [comment]
Yes, I understood. Thankyou

**Comment by anmoljhamb** [comment]
You're welcome.
